spring.application.name=Skill-6
server.port=2027

spring.datasource.url=jdbc:mysql://localhost:3306/labs
spring.datasource.username=root
spring.datasource.password=	veru

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true	
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect